name: RCON Test

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  rcon_test:
    runs-on: ubuntu-latest
    name: RCON Test
    steps:
      - name: Send Proxy RCON Command
        uses: MagicWorksMC/RCON-Action@v0.2.0
        continue-on-error: true
        with:
          server: ${{ secrets.PROXY_HOST }}      # Pulls from org secret
          port: ${{ secrets.PROXY_RCON_PORT }}        # Pulls from org secret
          password: ${{ secrets.RCON_PASSWORD }}  # Pulls from org secret
          send-push-info: false
          commands: '["glist all"]'

      - name: Send Staff RCON Command
        uses: MagicWorksMC/RCON-Action@v0.2.0
        continue-on-error: true
        with:
          server: ${{ secrets.MWPC_HOST }}      # Pulls from org secret
          port: ${{ secrets.STAFF_RCON_PORT }}        # Pulls from org secret
          password: ${{ secrets.RCON_PASSWORD }}  # Pulls from org secret
          send-push-info: false
          commands: '["saj hello"]'

